### ISSUE TITLE
test_deliver_after and test_deliver_at failed with latest Pulsar image

### ISSUE THREAD

**Issue by BewareMyPower** [apache/pulsar-client-python#234]
See https://github.com/BewareMyPower/pulsar-client-python/actions/runs/12278258523/job/34259522071?pr=7

```
======================================================================
FAIL: test_deliver_after (__main__.PulsarTest.test_deliver_after)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pulsar-client-python/pulsar-client-python/tests/pulsar_test.py", line 327, in test_deliver_after
    with self.assertRaises(pulsar.Timeout):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Timeout not raised

======================================================================
FAIL: test_deliver_at (__main__.PulsarTest.test_deliver_at)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/pulsar-client-python/pulsar-client-python/tests/pulsar_test.py", line 308, in test_deliver_at
    with self.assertRaises(pulsar.Timeout):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Timeout not raised
```

**Comment by BewareMyPower** [comment]
These tests passed after I switched back to the 4.0.0 image, see https://github.com/BewareMyPower/pulsar-client-python/actions/runs/12289443615/job/34294947018?pr=7
